Update basic.md
While defining const, 

const chart: Chart = new (window as any).G2.Chart({
      container: el,
      autoFit: true,
      height: 500,
      width: el.clientWidth,
      padding: [20, 120, 95],
    });


Throws an error as follows:

core.js:5967 ERROR TypeError: Cannot read property 'Chart' of undefined.

Hence replaced it with the "Chart" Class import from g2 as below

import { Chart } from '@antv/g2';

const chart: Chart = new Chart({
      container: el,
      autoFit: true,
      height: 500,
      width: el.clientWidth,
      padding: [20, 120, 95],
    });